### ISSUE TITLE
Erroneous parsing of unused selectors

### ISSUE THREAD

**Issue by HighPriest** [sass/embedded-host-node#343]
Dependencies:
```
"@sveltejs/kit": "npm:@sveltejs/kit@2.7.2",
"svelte": "npm:svelte@5.1.1",
"sveltekit-adapter-deno": "npm:sveltekit-adapter-deno@0.16.0",
"sass-embedded": "npm:sass-embedded@1.80.4",
```
SCSS style
```scss
h1, h2, h3, h4, p {
    width: 100%;
    display: flex;
    justify-content: center;
    margin: 0;
}
```

gets compiled into
```css
/* (unused) h1*/ h2.s-ISUD83oxX-r6, h3.s-ISUD83oxX-r6 /* (unused) h4*/ p.s-ISUD83oxX-r6 {
  width: 100%;
  display: flex;
  justify-content: center;
  margin: 0;
}
```

Take note of how the h4 tags appearance. A colon is missing between **h3** & **p**.  
This makes the **h3** & **p** selector not apply correctly.
